/*
 * PlotTest.kt
 * md (Android)
 *
 * The ```plot fence, against the oracle the site itself produced.
 *
 * WHERE THE EXPECTATIONS COME FROM
 * --------------------------------
 * `src/test/resources/plot-vectors.json` was generated by running
 * nettrash.me's own Rust — `render_plot_svg`, `nice_step`, `format_label` and
 * `preprocess_math_expr`, extracted verbatim from
 * `frontend/src/components/math.rs` — over 403 inputs: 81 tick spacings, 100
 * tick labels (each with the four Rust primitives that produced it), 162
 * evaluations, 38 malformed expressions and 22 whole figures. Every number in
 * it is recorded twice, once as JSON and once as the IEEE-754 bit pattern, so
 * "close enough" cannot creep in. The file is byte-identical to the copy in
 * `md.vscode/test/fixtures/`.
 *
 * It is an oracle, not a specification. Six of the behaviours it records are
 * bugs, and this suite asserts the **fixed** behaviour for those, in a table
 * that names each one and what the site did. Everything else must match the
 * vector exactly — there is no third category, and no row is skipped: a row
 * either matches its vector or appears in one of the correction tables below.
 *
 * This file mirrors `md.vscode/test/plot.test.ts` case for case, so a
 * divergence between the ports shows up as a failing assertion rather than as
 * two different figures. The one deliberate difference is the libm table: the
 * JVM's `Math` and Kotlin's `kotlin.math` are not V8's, and the rows where they
 * part company in the last bit are named below rather than tolerated wholesale.
 *
 * JSON is read by the hand-written parser at the foot of this file. The
 * unit-test classpath carries JUnit and nothing else — `org.json` is the
 * "not mocked" stub under `./gradlew test` — so a real parser is the only way
 * the corpus can be read at all, and it is thirty lines.
 */

package me.nettrash.md.markdown

import me.nettrash.md.book.EpubBook
import me.nettrash.md.book.EpubUnit
import me.nettrash.md.book.contentOpf
import me.nettrash.md.book.documentBody
import me.nettrash.md.book.toXhtml
import me.nettrash.md.book.xhtmlDocument
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.floor
import kotlin.math.log10

class PlotTest {

    // MARK: - The corpus

    private val vectors: JsonValue by lazy { loadVectors() }

    private fun loadVectors(): JsonValue {
        val stream = checkNotNull(javaClass.classLoader?.getResourceAsStream("plot-vectors.json")) {
            "missing plot-vectors.json"
        }
        return Json.parse(stream.bufferedReader(Charsets.UTF_8).use { it.readText() })
    }

    private fun rows(key: String): List<JsonValue> = vectors[key].array()

    /** `nan`, `inf` and `-inf` are JSON strings — JSON has no literal for them. */
    private fun real(value: JsonValue): Double = when {
        value.isString -> when (value.string()) {
            "nan" -> Double.NaN
            "inf" -> Double.POSITIVE_INFINITY
            "-inf" -> Double.NEGATIVE_INFINITY
            else -> throw AssertionError("not a number: ${value.string()}")
        }
        else -> value.number()
    }

    /** The big-endian IEEE-754 bit pattern, the way the vectors record a double. */
    private fun bits(value: Double): String = String.format("%016x", value.toRawBits())

    // MARK: - §1 nice_step — ported verbatim, so every row must match

    @Test fun niceStepReproducesAll81RecordedSpacingsBitForBit() {
        val recorded = rows("niceStep")
        assertEquals(81, recorded.size)
        for (row in recorded) {
            assertEquals(
                "niceStep(${row["input"]})",
                row["outputBits"].string(),
                bits(Plot.niceStep(real(row["input"]))),
            )
        }
    }

    /**
     * The decade is the mechanism, so the decade is what this pins.
     *
     * `9.999999999999999e-05` (bits 3f1a36e2eb1c432c) sits one ULP under 1e-4,
     * so the decade below it — the one [Plot.niceStep] must scale by — is 1e-5.
     * `floor(log10 …)` says −4 all the same, and the old code handed that
     * straight to a power function. `pow` is not correctly rounded and **is not
     * specified to be**, so `pow(10, n)` is a different double on different
     * *runtime versions*. Measured against the literal `1e<n>` over all 632
     * integer exponents in [-323, 308]: Node 20 disagrees at 68 of them on
     * arm64 and 69 on x86-64, Node 22 at 68, Node 24 at 2, Node 26 at none, and
     * OpenJDK 21 — this port's runtime — at 64, `StrictMath.pow` included. Not
     * a CPU difference: Node 20 is wrong on both architectures and Node 26 is
     * right on both. A wrong decade picks a different rung of the 1/2/5/10
     * ladder — a different step, a different number of ticks, different labels,
     * different bytes.
     *
     * This is a real failure, not a thought experiment: md.vscode's CI runs
     * Node 20 and is red on the pushed v1.2.0 (fd71a4e) with three failures in
     * `test/plot.test.ts`, `tiny_range` among them and an `xLabels` nine long
     * where this Mac — Node 26 — produces eight. Same source, same input, two
     * engine versions.
     *
     * The decade must therefore equal the **decimal literal**, whose parse is
     * specified to be correctly rounded in every language this renderer is
     * ported to. **`pow(10, e)` must never come back** — not in
     * `Plot.decadeOf`, not in `powerOfTen`, not anywhere the geometry can see
     * it.
     *
     * **What this pins, and what it does not.** It pins the *contract*: the
     * decade of the witness is the double that `"1e-5"` parses to, bit for bit,
     * and never 1e-4. It does not pin the *mechanism*. A `powerOfTen` rebuilt
     * on `Math.pow` fails here only because −5 happens to be one of OpenJDK
     * 21's 64 wrong exponents; on a runtime whose `pow` agreed with the literal
     * there — Darwin libm's is correct for all 632 — this assertion would pass
     * with `pow` in place and tell you nothing. The family's mechanism guard is
     * md.vscode's `test/plot.test.ts`, "gets the boundary decade right without
     * Math.pow, and survives a wrong log10": it replaces `Math.pow` with a
     * function that **throws**, so any reintroduction fails on every platform,
     * and it perturbs `log10` by ±1 decade while still demanding all 81 oracle
     * rows. Its CI runs Node 20, an affected engine. If you touch the decade
     * path here, run that one too.
     */
    @Test fun theDecadeOfABoundaryInputIsTheDecimalLiteralNotAPow() {
        val rough = java.lang.Double.longBitsToDouble(0x3f1a36e2eb1c432cL)
        assertEquals("the recorded witness", 9.999999999999999e-05, rough, 0.0)
        assertTrue("one ULP under 1e-4", rough < 1e-4)

        // What log10 on its own claims — an approximation, and here a wrong one.
        assertEquals("floor(log10) alone", -4.0, floor(log10(rough)), 0.0)

        // What the decade must be: the literal, bit for bit, however it is spelt.
        assertEquals("decadeOf", bits("1e-5".toDouble()), bits(Plot.decadeOf(rough)))
        assertEquals("the literal is the double", bits(1e-5), bits(Plot.decadeOf(rough)))

        // And the answer the unpinned code gave, which is what must not return.
        assertFalse("decade must not be 1e-4", Plot.decadeOf(rough) == 1e-4)
    }

    /**
     * The same pin across the whole exponent range the renderer can reach, on
     * both sides of every boundary: a power of ten is its own decade, and the
     * double just below it belongs to the decade beneath. 601 exponents,
     * [-300, 300], two inputs each.
     *
     * Expectations are spelt as parsed literals rather than computed, so the
     * test cannot agree with the code by sharing its mistake. It is still a
     * contract test rather than a mechanism test: it would catch a `Math.pow`
     * decade on *this* runtime — OpenJDK 21 disagrees with the literal at 62 of
     * these 601 exponents — but it would pass unchanged on a runtime whose
     * `pow` is correctly rounded. See the note on the previous test for the
     * guard that bites everywhere.
     */
    @Test fun everyDecadeBoundaryResolvesToTheLiteralOnBothSides() {
        for (exponent in -300..300) {
            val literal = "1e$exponent".toDouble()
            assertEquals("decadeOf(1e$exponent)", bits(literal), bits(Plot.decadeOf(literal)))
            assertEquals(
                "decadeOf(nextDown(1e$exponent))",
                bits("1e${exponent - 1}".toDouble()),
                bits(Plot.decadeOf(Math.nextDown(literal))),
            )
        }
    }

    /** The pin must be inert for the inputs `niceStep` cannot scale at all. */
    @Test fun theDecadePinLeavesDegenerateInputsAlone() {
        assertEquals("zero", bits(0.0), bits(Plot.decadeOf(0.0)))
        assertTrue("negative", Plot.decadeOf(-1.0).isNaN())
        assertTrue("nan", Plot.decadeOf(Double.NaN).isNaN())
        assertEquals("inf", bits(Double.POSITIVE_INFINITY), bits(Plot.decadeOf(Double.POSITIVE_INFINITY)))
        assertTrue("-inf", Plot.decadeOf(Double.NEGATIVE_INFINITY).isNaN())
    }

    @Test fun niceStepTakesEachOfTheFourBranches() {
        // norm <= 1.5, <= 3, <= 7, else — the `10 * mag` branch is the one a
        // careless port drops, and it is what draws [-32, 32] with a step of 10.
        assertEquals(1.0, Plot.niceStep(8.0), 0.0)
        assertEquals(2.0, Plot.niceStep(20.0), 0.0)
        assertEquals(5.0, Plot.niceStep(50.0), 0.0)
        assertEquals(10.0, Plot.niceStep(64.0), 0.0)
    }

    // MARK: - §2 format_label — ported with two corrections

    /**
     * The nine labels the site prints wrong, and what this renderer prints
     * instead.
     *
     * All nine are the same defect: `format_label`'s integer branch prints
     * `val as i64`, which **truncates**, so a tick that arrives one ULP below a
     * whole number loses a whole unit. SPEC §1.4 replaces the truncation with a
     * round, which is what `round()` in the same condition already implied.
     */
    private data class LabelFix(val input: Double, val site: String, val ours: String)

    private val correctedLabels = listOf(
        LabelFix(0.9999999999, "0", "1"),
        LabelFix(-0.9999999999, "0", "-1"),
        LabelFix(2.9999999996, "2", "3"),
        LabelFix(-2.9999999996, "-2", "-3"),
        LabelFix(999.9999999999, "999", "1000"),
        LabelFix(-999.9999999999, "-999", "-1000"),
        LabelFix(123.99999999995, "123", "124"),
        LabelFix(-123.99999999995, "-123", "-124"),
        LabelFix(999.9999999999999, "999", "1000"),
    )

    private fun correctedLabel(input: JsonValue): LabelFix? {
        if (input.isString) return null
        for (row in correctedLabels) if (row.input == input.number()) return row
        return null
    }

    @Test fun formatLabelReproducesAll100RecordedLabelsButForTheNineTheSiteTruncates() {
        val recorded = rows("formatLabel")
        assertEquals(100, recorded.size)
        var corrected = 0
        for (row in recorded) {
            val fix = correctedLabel(row["input"])
            val got = Plot.formatLabel(real(row["input"]))
            if (fix == null) {
                assertEquals("formatLabel(${row["input"]})", row["output"].string(), got)
            } else {
                assertEquals(
                    "the vector still records the site's ${row["input"]}",
                    fix.site,
                    row["output"].string(),
                )
                assertEquals("formatLabel(${row["input"]})", fix.ours, got)
                corrected++
            }
        }
        // Every row of the correction table was reached — a table entry that no
        // vector exercises is a claim about nothing.
        assertEquals(correctedLabels.size, corrected)
    }

    @Test fun formatLabelWritesRustsExponentialNotThePlatforms() {
        // THE cross-platform hazard, pinned on all 100 values: `1.0e3` and not
        // `1.0e+3` (JavaScript), `1.0e+03` (C, Java) or `1.0E3`; and ties to
        // even on the exact binary value, not the half-up rounding
        // `String.format` performs.
        for (row in rows("formatLabel")) {
            assertEquals(
                "{:.1e} of ${row["input"]}",
                row["rustPrimitives"]["fmt_1e"].string(),
                Plot.formatExponential(real(row["input"]), 1),
            )
        }
        // What the platform would have said.
        assertEquals("1.3e+03", String.format("%.1e", 1250.0))
        assertEquals("1.2e3", Plot.formatExponential(1250.0, 1)) // 1.25 → ties to even
        assertEquals("1.4e3", Plot.formatExponential(1350.0, 1)) // 1.35 → ties to even, upward
        assertEquals("1.3e-2", Plot.formatExponential(0.0125, 1)) // not a tie: the double is above it
        assertEquals("4.9e-324", Plot.formatExponential(4.9E-324, 1)) // the smallest subnormal
    }

    @Test fun formatLabelWritesRustsFixedFormNotStringFormat() {
        for (row in rows("formatLabel")) {
            // Past 25 significant digits `{:.2}` prints the double's whole exact
            // expansion (1e300 is 301 digits of it). `format_label` sends
            // everything from 1000 up to the exponential branch, so the fixed
            // formatter is never asked for one, and it stops at the digits it
            // can decide a rounding on.
            val expected = row["rustPrimitives"]["fmt_2f"].string()
            if (expected.length > 30) continue
            assertEquals("{:.2} of ${row["input"]}", expected, Plot.formatFixed(real(row["input"]), 2))
        }
        // What the platform would have said.
        assertEquals("0.13", String.format("%.2f", 0.125))
        assertEquals("0.12", Plot.formatFixed(0.125, 2)) // an exact tie, rounded to even
        assertEquals("8.12", Plot.formatFixed(8.125, 2))
        assertEquals("2.67", Plot.formatFixed(2.675, 2)) // the double is below the tie
        assertEquals("1000.00", Plot.formatFixed(999.999, 2)) // the carry runs off the fraction
        assertEquals("-0.00", Plot.formatFixed(-0.0, 2)) // Rust keeps the sign
    }

    // MARK: - §3 The expression language

    /**
     * The evaluations where this renderer deliberately answers differently.
     *
     * Four of the five families are SPEC §1.3's corrections; the fifth is the
     * `math::` prefix, which is not a language feature at all but the site's own
     * preprocessor showing through — it rewrites every roster name to `math::…`
     * before handing the text to evalexpr, so `math::sin(x)` happens to work
     * there. It is not in the roster, so it is a parse error here.
     */
    private data class EvalFix(val expr: String, val x: Double?, val value: Double, val why: String)

    private val correctedEval = listOf(
        // 1. floor / ceil / round draw. The site registers them bare and then
        //    asks evalexpr for `math::floor`, which is unbound, so all 1001
        //    samples fail and `broken_floor_no_curve.svg` has no polyline at all.
        EvalFix("floor(x)", 2.7, 2.0, "floor works"),
        EvalFix("floor(x)", -2.5, -3.0, "floor works"),
        EvalFix("ceil(x)", 2.1, 3.0, "ceil works"),
        EvalFix("ceil(x)", -2.5, -2.0, "ceil works"),
        EvalFix("round(x)", 2.5, 3.0, "round works, ties away from zero"),
        EvalFix("round(x)", -2.5, -3.0, "round works, ties away from zero"),
        EvalFix("round(x)", 0.5, 1.0, "round works, ties away from zero"),
        // 2. Comparisons and the Boolean operators are numbers, so they compose.
        EvalFix("x==1", 1.0, 1.0, "comparisons yield 1.0 / 0.0"),
        EvalFix("x!=1", 1.0, 0.0, "comparisons yield 1.0 / 0.0"),
        EvalFix("x<1", 0.0, 1.0, "comparisons yield 1.0 / 0.0"),
        EvalFix("x<=1", 1.0, 1.0, "comparisons yield 1.0 / 0.0"),
        EvalFix("x>1", 2.0, 1.0, "comparisons yield 1.0 / 0.0"),
        EvalFix("x>=1", 1.0, 1.0, "comparisons yield 1.0 / 0.0"),
        EvalFix("(x>0)*2", 1.0, 2.0, "a comparison multiplies"),
        EvalFix("!x", 1.0, 0.0, "negation is numeric"),
        EvalFix("1&&1", null, 1.0, "a number is a truth value"),
        EvalFix("1<2<3", null, 1.0, "comparisons chain left-associatively"),
        // 3. `^` is right-associative.
        EvalFix("2^3^2", null, 512.0, "2^(3^2), not (2^3)^2"),
        // 4. Everything is a double.
        EvalFix("5/2", null, 2.5, "no integer division"),
        EvalFix("-7/2", null, -3.5, "no integer division"),
        EvalFix("7/2", null, 3.5, "no integer division"),
        EvalFix("2+3*4-5/2", null, 11.5, "no integer division"),
        EvalFix("1/0", null, Double.POSITIVE_INFINITY, "division by zero is ±∞, not an error"),
        EvalFix("0/0", null, Double.NaN, "0/0 is NaN, not an error"),
        EvalFix("1%0", null, Double.NaN, "x%0 is NaN, not an error"),
    )

    /**
     * Expressions this language does not have.
     *
     * Every one of them is a **parse error** here, which is the point: on the
     * site most of these parse and then die silently at evaluation time, which
     * is why a typo currently looks like an empty chart rather than a message.
     */
    private val notInTheLanguage = listOf(
        // Not in the roster. evalexpr carries them; the four ports share a roster.
        "min(x,0)", "max(x,0)", "if(x>0,1,-1)", "log(8,2)", "typeof(x)",
        // The site's preprocessor showing through.
        "math::floor(x)", "math::sin(x)", "math::math::sin(x)", "math::log(8,2)",
        // Unknown names, and names that are nearly right.
        "mysin(x)", "x_sin(x)", "SIN(x)", "sinx", "foo(x)", "y", "X",
        "true&&false", "true||false", "!true",
        // Wrong arity — an error, not a silently empty chart.
        "sqrt(1,2)", "hypot(3)", "atan2(1)", "sin()",
        // Types and syntax the language has no use for.
        "\"abc\"", "(1,2)", "x=1", "0x10",
    )

    /**
     * Rows where the JVM's libm and Rust's libm disagree in the last bit.
     *
     * Six of 162, every one within one ULP, and every one a function neither
     * runtime rounds correctly. `Math.exp` and `Math.cosh` are the JVM's own
     * (both are specified only to within 1 ulp, and OpenJDK 21 on aarch64 lands
     * one ulp high on `exp(1)`); `asinh` and `atanh` are Kotlin's own
     * compositions of `ln` and `sqrt`; `asin` and `acos` are shared with the
     * TypeScript reference, which names the same two.
     *
     * Nothing can be done about it and nothing needs to be: one ULP is 10⁻¹⁶ of
     * a pixel coordinate, and the golden figure — 2002 coordinates, `exp` and
     * `sin` throughout — comes out byte-identical to the reference's anyway.
     * They are named rather than tolerated wholesale, so a *real* divergence in
     * any other function still fails.
     */
    private val libmUlp = listOf(
        "atanh(x)" to 0.5,
        "asin(x)" to 0.5,
        "acos(x)" to 0.5,
        "asinh(x)" to 1.0,
        "cosh(x)" to 1.0,
        "exp(x)" to 1.0,
    )

    private fun corrected(expr: String, x: Double): EvalFix? {
        for (row in correctedEval) {
            if (row.expr != expr) continue
            if (row.x != null && row.x != x) continue
            return row
        }
        return null
    }

    private fun isLibmRow(expr: String, x: Double): Boolean {
        for (row in libmUlp) if (row.first == expr && row.second == x) return true
        return false
    }

    private fun value(expr: String, x: Double): Double =
        Plot.evaluate(Plot.parseExpression(expr, "x"), "x", x)

    @Test fun theExpressionLanguageAccountsForAll162RecordedEvaluations() {
        val recorded = rows("eval")
        assertEquals(162, recorded.size)
        val seenCorrections = HashSet<String>()
        val seenAbsences = HashSet<String>()
        val failures = ArrayList<String>()

        for (row in recorded) {
            val expr = row["expr"].string()
            val x = real(row["x"])
            val label = "$expr at x=$x"

            val fix = corrected(expr, x)
            if (fix != null) {
                seenCorrections.add(expr)
                val got = value(expr, x)
                val ok = if (fix.value.isNaN()) got.isNaN() else got == fix.value
                if (!ok) failures.add("$label — ${fix.why}: got $got, wanted ${fix.value}")
                continue
            }

            if (notInTheLanguage.contains(expr)) {
                seenAbsences.add(expr)
                val threw = try {
                    value(expr, x)
                    false
                } catch (error: Plot.PlotError) {
                    assertNotNull(error.message)
                    true
                }
                if (!threw) failures.add("$label should have been a PlotError")
                continue
            }

            val want = real(row["result"])
            val got = value(expr, x)
            if (isLibmRow(expr, x)) {
                // Same value, possibly not the same last bit.
                if (!(Math.abs(got - want) / Math.abs(want) < 1e-15)) {
                    failures.add("$label — libm row is more than one ULP out: $got vs $want")
                }
                continue
            }
            if (want.isNaN()) {
                // NaN and not its payload: a runtime's libm may return a quiet
                // NaN spelt 7ffc000000000000 where Rust's returns
                // 7ff8000000000000, and no program can tell the difference.
                if (!got.isNaN()) failures.add("$label: got $got, wanted NaN")
                continue
            }
            if (bits(got) != row["resultBits"].string()) {
                failures.add("$label: got ${bits(got)} ($got), wanted ${row["resultBits"].string()} ($want)")
            }
        }

        assertTrue(failures.joinToString("\n"), failures.isEmpty())
        // Both tables are fully exercised by the corpus.
        assertEquals(correctedEval.map { it.expr }.toSet().size, seenCorrections.size)
        assertEquals(notInTheLanguage.size, seenAbsences.size)
    }

    @Test fun theExpressionLanguageRejectsEveryOneOfThe38MalformedExpressions() {
        val recorded = rows("parseErrors")
        assertEquals(38, recorded.size)
        for (row in recorded) {
            val expr = row["expr"].string()
            // Two of the site's failures are not failures here, and both are in
            // the grammar on purpose: `floor(x)` is correction 1, and `x ++ 2`
            // is `x + (+2)` — unary plus is a prefix operator in SPEC §1.3's
            // table.
            if (expr == "floor(x)" || expr == "x ++ 2") continue
            assertThrowsPlotError(expr) { value(expr, 1.0) }
        }
    }

    @Test fun theExpressionLanguageSaysWhatIsWrongInTheWordsSpec17Uses() {
        assertMessage("unknown function 'sinc'") { value("sinc(x)", 1.0) }
        assertMessage("expected ')'") { value("sin(x", 1.0) }
        assertMessage("sqrt takes 1 argument, not 2") { value("sqrt(1,2)", 1.0) }
        assertMessage("unknown name 'y'") { value("y", 1.0) }
    }

    @Test fun theExpressionLanguageBindsUnaryMinusLooserThanPowerAndPowerToTheRight() {
        assertEquals(512.0, value("2^3^2", 0.0), 0.0)
        assertEquals(512.0, value("2^(3^2)", 0.0), 0.0)
        assertEquals(64.0, value("(2^3)^2", 0.0), 0.0)
        assertEquals(-9.0, value("-x^2", 3.0), 0.0)
        assertEquals(9.0, value("(-x)^2", 3.0), 0.0)
        assertEquals(-4.0, value("-2^2", 0.0), 0.0)
        assertEquals(0.5, value("2^-1", 0.0), 0.0)
        assertEquals(-3.0, value("-x", 3.0), 0.0)
        assertEquals(3.0, value("--x", 3.0), 0.0)
    }

    /**
     * The five arguments where `Math.pow` is not IEEE 754's `pow`.
     *
     * C99 §F.9.4.4 and IEEE 754-2008 both say `pow(+1, y)` is 1 for **any** y —
     * ±∞ and NaN included — and that `pow(-1, ±∞)` is 1. Swift and Rust do that
     * (both are C's `pow` underneath); Java and JavaScript answer NaN to all
     * five, Java by an explicit clause in `Math.pow`'s contract ("if the
     * absolute value of the first argument equals 1 and the second argument is
     * infinite, then the result is NaN"). SPEC §1.3 makes every value here an
     * IEEE-754 double, so the two ports that agree with IEEE are the right ones
     * and this one is corrected to match. `Plot.powIEEE` is what does it, and
     * both spellings — the `^` operator and the `pow(a,b)` function — go
     * through it.
     *
     * `plot-vectors.json` has no row for any of the five, so this is not a
     * correction *against* the oracle; it is a case the oracle never reached.
     */
    @Test fun powIsOneForEveryExponentOfPositiveOneAndForInfinitePowersOfMinusOne() {
        val inf = Double.POSITIVE_INFINITY
        // pow(1, NaN) — the only NaN argument in all of arithmetic that is not
        // contagious.
        assertEquals(1.0, value("pow(1,x)", Double.NaN), 0.0)
        assertEquals(1.0, value("1^x", Double.NaN), 0.0)
        // pow(1, +inf)
        assertEquals(1.0, value("pow(1,x)", inf), 0.0)
        assertEquals(1.0, value("1^x", inf), 0.0)
        // pow(1, -inf)
        assertEquals(1.0, value("pow(1,x)", -inf), 0.0)
        assertEquals(1.0, value("1^x", -inf), 0.0)
        // pow(-1, +inf)
        assertEquals(1.0, value("pow(-1,x)", inf), 0.0)
        assertEquals(1.0, value("(-1)^x", inf), 0.0)
        // pow(-1, -inf)
        assertEquals(1.0, value("pow(-1,x)", -inf), 0.0)
        assertEquals(1.0, value("(-1)^x", -inf), 0.0)
        // Reached through an expression rather than a literal, because that is
        // how a curve actually walks into it: 1^(1/x) at x = 0.
        assertEquals(1.0, value("1^(1/x)", 0.0), 0.0)

        // And nothing else moves. Every neighbouring special case keeps IEEE's
        // own answer, which for these Java already gives.
        assertTrue(value("pow(x,x)", Double.NaN).isNaN()) // NaN^NaN is NaN
        assertEquals(inf, value("(-1.0000001)^x", inf), 0.0) // |base| > 1 → +∞
        assertEquals(0.0, value("(-1.0000001)^x", -inf), 0.0)
        assertTrue(value("pow(-1,x)", Double.NaN).isNaN()) // (-1)^NaN stays NaN
        assertEquals(1.0, value("pow(x,0)", Double.NaN), 0.0) // NaN^0 is 1, as Java already has it
        assertEquals(1.0, value("0^0", 0.0), 0.0)
        assertEquals(1024.0, value("2^10", 0.0), 0.0)
        assertTrue(value("pow(x,0.5)", -8.0).isNaN())
    }

    @Test fun theExpressionLanguageKnowsPiAndENothingElseWithoutParentheses() {
        assertEquals(Math.PI, value("pi", 0.0), 0.0)
        assertEquals(Math.E, value("e", 0.0), 0.0)
        assertEquals(7.3890560989306495, value("e^2", 0.0), 0.0)
        assertMessage("sin is a function") { value("sin", 0.0) }
    }

    // MARK: - §4 The four corrected behaviours, as figures

    /** Everything a rendered figure can be asked about without an XML parser. */
    private class Facts(
        val lines: Int,
        val texts: Int,
        val polylines: Int,
        val first: String?,
        val last: String?,
        val xLabels: List<String>,
        val yLabels: List<String>,
    )

    private fun facts(svg: String): Facts {
        val runs = allGroups(svg, "<polyline points=\"", "\"")
        val lastRun = runs.lastOrNull()?.split(" ")
        return Facts(
            lines = countOf(svg, "<line "),
            texts = countOf(svg, "<text "),
            polylines = runs.size,
            first = runs.firstOrNull()?.split(" ")?.firstOrNull(),
            last = lastRun?.lastOrNull(),
            xLabels = allGroups(svg, "text-anchor=\"middle\">", "</text>"),
            yLabels = allGroups(svg, "dominant-baseline=\"middle\">", "</text>"),
        )
    }

    private fun figure(source: String): Facts = facts(Plot.plotSVG(source))

    @Test fun correction1FloorCeilAndRoundDrawACurveWhereTheSiteDrawsNothing() {
        // `broken_floor_no_curve.svg` has 0 polylines. Here the staircase is one
        // run: floor(x) stays inside [-2, 2] for x in [-2, 3), and every step
        // lands inside the window, so nothing breaks it.
        val floor = figure("x: -10..10\ny: -2..2\nfloor(x)")
        assertEquals(1, floor.polylines)
        assertEquals("248.00,360.00", floor.first) // x = -2, y = -2: the bottom left
        assertEquals("377.48,40.00", floor.last) // x = 2.98, y = 2: the top of the last step
        assertTrue(figure("x: -10..10\ny: -2..2\nceil(x)").polylines > 0)
        assertTrue(figure("x: -10..10\ny: -2..2\nround(x)").polylines > 0)
    }

    @Test fun correction2AComparisonIsANumberSoTheHalfDomainIdiomDraws() {
        // `boolean_no_curve.svg` has 0 polylines for `x>0`.
        val step = figure("x: -10..10\ny: -2..2\nx>0")
        assertEquals(1, step.polylines)
        assertEquals("40.00,200.00", step.first) // 0 at the far left
        assertEquals("560.00,120.00", step.last) // 1 at the far right

        // The spec's own idiom. It draws exactly the half-domain it names: NaN
        // times zero is still NaN, so the left half stays empty and the curve
        // begins at the origin.
        val half = figure("x: -4..4\ny: -1..3\n(x>0)*sqrt(x)")
        assertEquals(1, half.polylines)
        assertEquals("300.00,280.00", half.first) // x = 0, y = 0
        assertEquals("560.00,120.00", half.last) // x = 4, y = 2

        // And where the guard has a finite value on both sides it is a
        // full-width curve with a kink — a rectifier, drawn from edge to edge.
        val relu = figure("x: -4..4\ny: -1..3\n(x>0)*x")
        assertEquals(1, relu.polylines)
        assertEquals("40.00,280.00", relu.first)
        // …until it climbs out of the window at y = 3, which is where the run ends.
        assertEquals("495.00,40.00", relu.last)
    }

    @Test fun correction3PowerIs512InAFigureNot64() {
        // A constant series is a flat line, so its height *is* the value: with
        // y: 0..1024 the line at 512 lands exactly halfway.
        val chart = figure("x: -1..1\ny: 0..1024\n2^3^2")
        assertEquals("40.00,200.00", chart.first)
        assertEquals("560.00,200.00", chart.last)
    }

    @Test fun correction4FiveOverTwoIsTwoPointFiveAndTheSiteDrawsItAtTwo() {
        // `int_division_trunc.svg` puts the line at y = 232, which is sy(2).
        val chart = figure("x: -1..1\ny: 0..5\n5/2")
        assertEquals("40.00,200.00", chart.first) // sy(2.5)
        assertEquals("560.00,200.00", chart.last)
    }

    @Test fun axisCorrectionLabelsATickAtMinusFourWhereTheSiteTruncatesToMinusThree() {
        // `tick_label_truncation.svg`, both axes [-5, -3]: the site's sixth
        // label reads "-3", out of order, in the middle of the axis.
        val chart = figure("x: -5..-3\ny: -5..-3\nx")
        assertEquals("-4", chart.xLabels[5])
        assertEquals("-4", chart.yLabels[5])
        assertEquals(
            listOf("-5", "-4.80", "-4.60", "-4.40", "-4.20", "-4", "-3.80", "-3.60", "-3.40", "-3.20", "-3"),
            chart.xLabels,
        )
    }

    @Test fun axisCorrectionLabelsTheTickAtTheOriginZeroWhereTheSiteDriftsTo56e17() {
        // `tick_drift_zero_label.svg`: `gx += step` over [-1, 1] at 0.2 never
        // lands on zero. `first + i * step` does.
        val chart = figure("x: -1..1\ny: -1..1\nx")
        assertEquals("0", chart.xLabels[5])
        assertEquals("0", chart.yLabels[5])
        // And `tick_drift_extra_tick.svg`, where the drift is 1.4e-16 instead.
        assertEquals("0", figure("x: -0.9..0.3\ny: -0.9..0.3\nx").xLabels[9])
    }

    @Test fun axisCorrectionKeepsTheTickThatLandsExactlyOnTheMaximum() {
        // The other half of computing by index: `0.0001 + 8 * 0.0001` is
        // 9.000000000000001e-4, a hair over the range's own maximum, and
        // dropping the last tick of an axis because of one ULP is a visible
        // defect. The site drops it (`tiny_range.svg` has eight ticks per axis).
        val chart = figure("x: 0.0001..0.0009\ny: 0.0001..0.0009\nx")
        assertEquals(9, chart.xLabels.size)
        assertEquals("9.0e-4", chart.xLabels[8])
    }

    // MARK: - §5 The 22 recorded figures

    /**
     * The figures whose recorded shape is one of the six corrected behaviours.
     *
     * Each entry lists only what differs from the vector; everything unlisted is
     * still asserted against the site's own numbers.
     */
    private class FigureFix(
        val polylines: Int? = null,
        val first: String? = null,
        val last: String? = null,
        val lines: Int? = null,
        val texts: Int? = null,
        val xLabels: List<String>? = null,
        val yLabels: List<String>? = null,
        @Suppress("unused") val why: String = "",
    )

    private val minusOneToOne =
        listOf("-1", "-0.80", "-0.60", "-0.40", "-0.20", "0", "0.20", "0.40", "0.60", "0.80", "1")
    private val minusNineToThree = listOf(
        "-0.90", "-0.80", "-0.70", "-0.60", "-0.50", "-0.40", "-0.30", "-0.20", "-0.10", "0",
        "0.10", "0.20", "0.30",
    )
    private val minusFiveToMinusThree =
        listOf("-5", "-4.80", "-4.60", "-4.40", "-4.20", "-4", "-3.80", "-3.60", "-3.40", "-3.20", "-3")
    private val tinyRangeLabels = listOf(
        "1.0e-4", "2.0e-4", "3.0e-4", "4.0e-4", "5.0e-4", "6.0e-4", "7.0e-4", "8.0e-4", "9.0e-4",
    )

    private val correctedFigures: Map<String, FigureFix> = mapOf(
        // floor(x) draws (correction 1).
        "broken_floor_no_curve" to FigureFix(
            polylines = 1, first = "248.00,360.00", last = "377.48,40.00", why = "floor is bound",
        ),
        // x>0 draws (correction 2).
        "boolean_no_curve" to FigureFix(
            polylines = 1, first = "40.00,200.00", last = "560.00,120.00",
            why = "a comparison is a number",
        ),
        // 5/2 is 2.5, and the origin's label is "0" and not "-5.6e-17".
        "int_division_trunc" to FigureFix(
            first = "40.00,200.00", last = "560.00,200.00", xLabels = minusOneToOne,
            why = "no integer division; no tick drift",
        ),
        "constant_three" to FigureFix(xLabels = minusOneToOne, why = "no tick drift"),
        "tick_drift_zero_label" to FigureFix(
            xLabels = minusOneToOne, yLabels = minusOneToOne, why = "no tick drift",
        ),
        "tick_drift_extra_tick" to FigureFix(
            xLabels = minusNineToThree, yLabels = minusNineToThree, why = "no tick drift",
        ),
        // The truncated label, and the tick at the maximum the site's
        // accumulation overshot: eleven ticks per axis rather than ten.
        "tick_label_truncation" to FigureFix(
            lines = 22, texts = 22, xLabels = minusFiveToMinusThree, yLabels = minusFiveToMinusThree,
            why = "labels are rounded, and the last tick is kept",
        ),
        "no_zero_on_either_axis" to FigureFix(
            lines = 20, texts = 20,
            xLabels = listOf("1", "1.20", "1.40", "1.60", "1.80", "2", "2.20", "2.40", "2.60", "2.80", "3"),
            why = "labels are rounded, and the last tick is kept",
        ),
        "tiny_range" to FigureFix(
            lines = 18, texts = 18, xLabels = tinyRangeLabels, yLabels = tinyRangeLabels,
            why = "the tick on the maximum is kept",
        ),
    )

    @Test fun thirteenOfTheTwentyTwoRecordedFiguresAreDrawnExactlyAsTheSiteDoes() {
        val recorded = rows("svg")
        assertEquals(22, recorded.size)
        var same = 0
        for (row in recorded) if (!correctedFigures.containsKey(row["name"].string())) same++
        assertEquals(13, same)
    }

    /**
     * One recorded figure, rebuilt from the range the generator wrote and
     * compared against every number it recorded.
     *
     * The range is rebuilt from the *literal* in the JSON rather than from a
     * re-formatted double, so `0.7999999999999998` reaches the parser as the
     * generator spelt it.
     */
    private fun assertFigure(name: String) {
        val row = rows("svg").first { it["name"].string() == name }
        val source = "x: ${row["xMin"].raw()}..${row["xMax"].raw()}\n" +
            "y: ${row["yMin"].raw()}..${row["yMax"].raw()}\n${row["expr"].string()}"
        val got = facts(Plot.plotSVG(source))
        val fix = correctedFigures[name] ?: FigureFix()

        // The spacing is `nice_step`, ported verbatim: never corrected.
        assertEquals(
            "$name x spacing",
            bits(row["xStep"].number()),
            bits(Plot.niceStep(row["xMax"].number() - row["xMin"].number())),
        )
        assertEquals(
            "$name y spacing",
            bits(row["yStep"].number()),
            bits(Plot.niceStep(row["yMax"].number() - row["yMin"].number())),
        )

        assertEquals("$name grid + axis lines", fix.lines ?: row["lineCount"].int(), got.lines)
        assertEquals("$name tick labels", fix.texts ?: row["textCount"].int(), got.texts)
        assertEquals("$name unbroken runs", fix.polylines ?: row["polylineCount"].int(), got.polylines)
        assertEquals("$name first plotted point", fix.first ?: row["firstPoint"].stringOrNull(), got.first)
        assertEquals("$name last plotted point", fix.last ?: row["lastPoint"].stringOrNull(), got.last)
        assertEquals("$name x tick labels", fix.xLabels ?: row["xTickLabels"].strings(), got.xLabels)
        assertEquals("$name y tick labels", fix.yLabels ?: row["yTickLabels"].strings(), got.yLabels)
    }

    /** The roster the twenty-two cases below cover, pinned against the corpus:
     *  the reference generates one test per row, so a row this suite never
     *  named would be a row nobody checks. */
    private val figureNames = listOf(
        "default_sin",
        "tan_many_breaks",
        "one_over_x_break_at_0",
        "x_squared_leaves_window",
        "constant_three",
        "flat_zero",
        "no_zero_on_either_axis",
        "nice_step_ten_branch",
        "sqrt_nan_half",
        "single_point_run",
        "broken_floor_no_curve",
        "boolean_no_curve",
        "ln_positive_domain",
        "int_division_trunc",
        "tiny_range",
        "big_range",
        "pi_e_constants",
        "asymmetric_offset",
        "tick_drift_zero_label",
        "tick_label_truncation",
        "tick_drift_extra_tick",
        "sampling_formula_sensitive",
    )

    @Test fun everyRecordedFigureHasACaseOfItsOwn() {
        assertEquals(figureNames, rows("svg").map { it["name"].string() })
    }

    @Test fun figureDefaultSin() = assertFigure("default_sin")

    @Test fun figureTanManyBreaks() = assertFigure("tan_many_breaks")

    @Test fun figureOneOverXBreakAt0() = assertFigure("one_over_x_break_at_0")

    @Test fun figureXSquaredLeavesWindow() = assertFigure("x_squared_leaves_window")

    @Test fun figureConstantThree() = assertFigure("constant_three")

    @Test fun figureFlatZero() = assertFigure("flat_zero")

    @Test fun figureNoZeroOnEitherAxis() = assertFigure("no_zero_on_either_axis")

    @Test fun figureNiceStepTenBranch() = assertFigure("nice_step_ten_branch")

    @Test fun figureSqrtNanHalf() = assertFigure("sqrt_nan_half")

    @Test fun figureSinglePointRun() = assertFigure("single_point_run")

    @Test fun figureBrokenFloorNoCurve() = assertFigure("broken_floor_no_curve")

    @Test fun figureBooleanNoCurve() = assertFigure("boolean_no_curve")

    @Test fun figureLnPositiveDomain() = assertFigure("ln_positive_domain")

    @Test fun figureIntDivisionTrunc() = assertFigure("int_division_trunc")

    @Test fun figureTinyRange() = assertFigure("tiny_range")

    @Test fun figureBigRange() = assertFigure("big_range")

    @Test fun figurePiEConstants() = assertFigure("pi_e_constants")

    @Test fun figureAsymmetricOffset() = assertFigure("asymmetric_offset")

    @Test fun figureTickDriftZeroLabel() = assertFigure("tick_drift_zero_label")

    @Test fun figureTickLabelTruncation() = assertFigure("tick_label_truncation")

    @Test fun figureTickDriftExtraTick() = assertFigure("tick_drift_extra_tick")

    @Test fun figureSamplingFormulaSensitive() = assertFigure("sampling_formula_sensitive")

    @Test fun breaksACurveWhereItLeavesTheWindowAndNowhereElse() {
        // tan(x) over [-10, 10] is seven branches; 1/x over [-5, 5] is two; a
        // single plottable sample is still a polyline of one point.
        assertEquals(7, figure("x: -10..10\ny: -2..2\ntan(x)").polylines)
        assertEquals(2, figure("x: -5..5\ny: -5..5\n1/x").polylines)
        assertEquals("300.00,200.00", figure("x: -10..10\ny: -0.005..0.005\nx").first)
    }

    @Test fun samplesWithTheFormulaTheSiteUsesNotTheCheaperOne() {
        // `xMin + (i / samples) * span`, never `xMin + i * dx`: the two differ
        // in the last bits for 221 of the 1001 default samples, and the
        // difference reaches the output.
        val chart = figure("x: -6.3..0.7999999999999998\ny: -3.3..3.1\nx")
        assertEquals("259.96,359.83", chart.first)
        assertEquals("560.00,155.00", chart.last)
    }

    // MARK: - §6 The fence

    @Test fun readsDirectivesInAnyOrderAndIgnoresBlanksAndComments() {
        val spec = Plot.parsePlot(
            listOf("# a comment", "", "sin(x)", "title: A title", "x: -1..1", "y: -2..2", "")
                .joinToString("\n"),
        )
        assertEquals("A title", spec.title)
        assertEquals(-1.0, spec.xMin, 0.0)
        assertEquals(1.0, spec.xMax, 0.0)
        assertEquals(-2.0, spec.yMin!!, 0.0)
        assertEquals(1, spec.series.size)
    }

    @Test fun treatsAnUnknownKeyLineAsALabelledSeriesNotAsAnError() {
        // `f: x` still plots. This is why the directive scan checks the key
        // against the known list before it claims the line, and why the series
        // parser then reads the key as a label.
        val spec = Plot.parsePlot("f: x")
        assertEquals(1, spec.series.size)
        assertEquals("f", spec.series[0].label)
        assertEquals("x", spec.series[0].source)
        assertTrue(Plot.plotSVG("f: sin(x)").contains("<polyline"))
    }

    @Test fun defaultsToMinusTenToTenAutoSixHundredByFourHundredAndAThousandSamples() {
        val spec = Plot.parsePlot("sin(x)")
        assertEquals(-10.0, spec.xMin, 0.0)
        assertEquals(10.0, spec.xMax, 0.0)
        assertNull(spec.yMin)
        assertEquals(600, spec.width)
        assertEquals(400, spec.height)
        assertEquals(1000, spec.samples)
        assertEquals(Plot.Legend.AUTO, spec.legend)
        assertTrue(spec.grid)
        assertTrue(spec.axes)
    }

    @Test fun clampsWidthHeightAndSamples() {
        val small = Plot.parsePlot("width: 10\nheight: 10\nsamples: 1\nx")
        assertEquals(160, small.width)
        assertEquals(120, small.height)
        assertEquals(50, small.samples)
        val large = Plot.parsePlot("width: 9000\nheight: 9000\nsamples: 90000\nx")
        assertEquals(2000, large.width)
        assertEquals(2000, large.height)
        assertEquals(5000, large.samples)
    }

    @Test fun takesAConstantExpressionAtEitherEndOfARange() {
        val spec = Plot.parsePlot("x: -pi..2*pi\nsin(x)")
        assertEquals(-Math.PI, spec.xMin, 0.0)
        assertEquals(2 * Math.PI, spec.xMax, 0.0)
    }

    @Test fun rejectsARangeThatDoesNotIncrease() {
        assertMessage("x range must be increasing") { Plot.parsePlot("x: 1..1\nx") }
        assertMessage("y range must be increasing") { Plot.parsePlot("y: 5..-5\nx") }
        assertThrowsPlotError("x: nonsense") { Plot.parsePlot("x: nonsense\nx") }
    }

    @Test fun splitsALabelOffTheFirstTopLevelBareEquals() {
        assertEquals("envelope", Plot.parsePlot("envelope = exp(-abs(x)/5)").series[0].label)
        assertEquals("exp(-abs(x)/5)", Plot.parsePlot("envelope = exp(-abs(x)/5)").series[0].source)
        // The FIRST one, so what follows still has to be an expression: there is
        // no assignment in the language for a second `=` to be part of.
        assertThrowsPlotError("a = b = x") { Plot.parsePlot("a = b = x") }
        // …and never off a comparison operator.
        for (source in listOf("x == 1", "x <= 1", "x >= 1", "x != 1")) {
            assertEquals(source, null, Plot.parsePlot(source).series[0].label)
        }
    }

    @Test fun readsAPointsSeriesAndAParametricSeries() {
        val points = Plot.parsePlot("measured = points: 0,0 1,2 2,1").series[0]
        assertEquals(Plot.SeriesKind.POINTS, points.kind)
        assertEquals("measured", points.label)
        assertEquals(
            listOf(Plot.Point(0.0, 0.0), Plot.Point(1.0, 2.0), Plot.Point(2.0, 1.0)),
            points.points,
        )

        val parametric = Plot.parsePlot("circle = (cos(t), sin(t)) for t in 0..2*pi").series[0]
        assertEquals(Plot.SeriesKind.PARAMETRIC, parametric.kind)
        assertEquals("t", parametric.parameter)
        assertEquals(0.0, parametric.tMin, 0.0)
        assertEquals(2 * Math.PI, parametric.tMax, 0.0)
        // The parametric variable is the only free name inside it: `x` is not.
        assertMessage("unknown name 'x'") { Plot.parsePlot("(x, sin(t)) for t in 0..1") }
    }

    @Test fun doesNotMistakeAParenthesisedExpressionForAParametricOne() {
        assertEquals(Plot.SeriesKind.FUNCTION, Plot.parsePlot("(x+1)*2").series[0].kind)
        // A pair with no `for` is not a parametric series, so it is read as an
        // expression — and a tuple is not one of those.
        assertThrowsPlotError("(x, x)") { Plot.parsePlot("(x, x)") }
    }

    @Test fun fitsYAutoToTheFiniteSamplesWithFivePercentOfPadding() {
        // sin over a whole period reaches ±1 (to the last sample), so the window
        // is 1.05 either way.
        assertTrue(Plot.plotSVG("x: -10..10\nsin(x)").contains(">1</text>"))
        // A series with nothing finite in it falls back to -1..1.
        assertTrue(Plot.plotSVG("x: -10..10\nsqrt(-1)+x*0").contains(">1</text>"))
        // A flat series has no span to take 5 % of: it is padded by 5 % of itself.
        assertEquals(1, Plot.parsePlot("x: -1..1\n3").series.size)
        assertTrue(Plot.plotSVG("x: -1..1\n3").contains("<polyline"))
    }

    @Test fun showsTheLegendWhenThereAreTwoSeriesOrOneThatIsLabelled() {
        val legendGroup = "font-size=\"11\" font-family=\"sans-serif\""
        assertFalse(Plot.plotSVG("x: -1..1\nsin(x)").contains(legendGroup))
        assertTrue(Plot.plotSVG("x: -1..1\nsin(x)\ncos(x)").contains(legendGroup))
        assertTrue(Plot.plotSVG("x: -1..1\nwave = sin(x)").contains(">wave</text>"))
        assertFalse(Plot.plotSVG("x: -1..1\nlegend: off\nsin(x)\ncos(x)").contains(legendGroup))
        // An unlabelled series' legend text is its own source.
        assertTrue(Plot.plotSVG("x: -1..1\nlegend: on\nsin(x)").contains(">sin(x)</text>"))
    }

    @Test fun turnsTheGridAndTheAxesOff() {
        val bare = Plot.plotSVG("x: -1..1\ngrid: off\naxes: off\nx")
        assertFalse(bare.contains("<line"))
        assertFalse(bare.contains("<text x="))
        assertFalse(bare.contains("<rect"))
        assertTrue(bare.contains("<polyline"))
        assertMessage("grid must be 'on' or 'off'") { Plot.parsePlot("grid: sometimes\nx") }
    }

    @Test fun givesEachSeriesTheNextColourPurpleFirst() {
        val svg = Plot.plotSVG("x: -1..1\nx\nx+0.1\nx+0.2")
        assertTrue(svg.contains("stroke=\"#673AB7\""))
        assertTrue(svg.contains("stroke=\"#E5390F\""))
        assertTrue(svg.contains("stroke=\"#0F9D58\""))
    }

    // MARK: - §7 The container, and what must never be in it

    private val sampleSvg = Plot.plotSVG("x: -10..10\ntitle: T\nsin(x)")

    @Test fun isADivPlotAroundOneSvgWithAViewBox() {
        val block = Plot.renderPlot("x: -10..10\nsin(x)")
        assertTrue(block.startsWith("<div class=\"plot\"><svg "))
        assertTrue(block.endsWith("</svg></div>"))
        // Without a viewBox, `max-width: 100%; height: auto` shrinks the box and
        // clips the drawing instead of scaling it.
        assertTrue(block.contains("viewBox=\"0 0 600 400\""))
        assertTrue(block.contains("width=\"600\" height=\"400\" role=\"img\""))
    }

    @Test fun carriesNoIdAtAll() {
        // SPEC §1.5: a duplicated id is how one figure ends up wearing another's
        // clip path once a document holds two plots. An `<svg role="img">` is
        // named by its own `<title>`, with no `aria-labelledby` to point at, so
        // there is nothing to number.
        val two = Plot.renderPlot("sin(x)") + Plot.renderPlot("cos(x)")
        assertFalse(two.contains(" id="))
        assertFalse(two.contains("aria-labelledby"))
        assertTrue(sampleSvg.contains("<title>T</title>"))
        assertTrue(Plot.plotSVG("sin(x)").contains("<title>Plot of sin(x)</title>"))
    }

    @Test fun paintsWithCurrentColorAndBakesOnlyTheSeriesColours() {
        // `renderBlock` is theme-blind in all four repos, so one SVG has to be
        // right in a light preview, a dark preview, print, an exported page and
        // a saved file. A baked grey is a light-mode assumption.
        assertTrue(sampleSvg.contains("stroke=\"currentColor\""))
        assertTrue(sampleSvg.contains("fill=\"currentColor\""))
        for (grey in listOf("#e0e0e0", "#999", "#666", "#ccc")) {
            assertFalse(grey, sampleSvg.contains(grey))
        }
        assertFalse(sampleSvg.contains("background:white"))
        assertTrue(sampleSvg.contains("stroke=\"#673AB7\""))
    }

    @Test fun embedsNoStyleScriptForeignObjectOrFont() {
        // An SVG `<style>` inside an HTML document is document-scoped and leaks.
        for (forbidden in listOf("<style", "<script", "<foreignObject", "@font-face", "<image")) {
            assertFalse(forbidden, sampleSvg.contains(forbidden))
        }
    }

    @Test fun xmlEscapesEveryAuthorStringWithTheFiveXmlEntitiesAndNoOther() {
        // The EPUB body is XHTML, which is XML: one raw `&` makes the whole
        // content document unparseable and the book unopenable. And a named
        // entity like `&nbsp;` is undefined in XML, so escaping may only ever
        // produce the five.
        val hostile = Plot.plotSVG(
            listOf("title: A & B <c> \"d\"", "xlabel: <x>", "ylabel: &y;", "p & q = x").joinToString("\n"),
        )
        assertTrue(hostile.contains("<title>A &amp; B &lt;c&gt; &quot;d&quot;</title>"))
        assertTrue(hostile.contains(">&lt;x&gt;</text>"))
        assertTrue(hostile.contains(">&amp;y;</text>"))
        assertTrue(hostile.contains(">p &amp; q</text>"))
        assertFalse(hostile.contains("&nbsp;"))
        for (entity in Regex("&[a-z]+;").findAll(hostile).map { it.value }) {
            assertTrue(entity, entity in listOf("&amp;", "&lt;", "&gt;", "&quot;", "&apos;"))
        }
    }

    @Test fun emitsTheContainerEvenForAnEmptyBlockAndABrokenOne() {
        // If it is ever omitted the SVG-export ordinals desynchronise and every
        // later diagram exports the wrong figure.
        assertEquals("<div class=\"plot\"></div>", Plot.renderPlot(""))
        assertEquals("<div class=\"plot\"></div>", Plot.renderPlot("# only a comment"))
        val broken = Plot.renderPlot("sinc(x)")
        assertTrue(broken.startsWith("<div class=\"plot\"><pre>"))
        assertTrue(broken.contains("plot: unknown function 'sinc'"))
        assertTrue(broken.contains("sinc(x)")) // the source always stays visible
        assertTrue(Plot.renderPlot("x: 1..1\nx").contains("plot: x range must be increasing"))
    }

    @Test fun escapesTheSourceItFallsBackTo() {
        assertTrue(Plot.renderPlot("<b>&</b>").contains("&lt;b&gt;&amp;&lt;/b&gt;"))
    }

    @Test fun neverReturnsAnythingButAContainerWhateverItIsHanded() {
        // The renderer runs inside the Markdown renderer, which has no other
        // failure mode: whatever a fence contains, the answer is a `div.plot`
        // with either a drawing or the source in it, and every coordinate in
        // that drawing is a real number. A stack overflow on 200 nested
        // parentheses is caught by the depth budget here — on this platform it
        // would be a crash, not an exception — and the author's own text still
        // comes back.
        val hostile = listOf(
            "", "   ", "#", "x: 0..0\nx", "y: 1..0\nx", "width: -5\nheight: abc\nx",
            "points:", "points: 1", "label =", "= x", "(cos(t), sin(t)) for t in 0..0",
            "(cos(t), sin(t)) for u in 0..1", "x: 1e308..-1e308\nx", "x: -1e308..1e308\nx",
            "x: 0.0000001..0.0000002\nx", "axes: off\ngrid: off\nx", "ln(x)", "x^x",
            "sqrt(-x)", "0/0", "x*0/0", "(".repeat(200) + "x", "title: " + "A".repeat(500) + "\nx",
            "y: -1..1\n" + "sin(x)\n".repeat(12),
        )
        val attribute = Regex(" (?:x|y|x1|y1|x2|y2|width|height|cx|cy)=\"([^\"]*)\"")
        for (source in hostile) {
            val html = Plot.renderPlot(source)
            assertTrue(source, html.startsWith("<div class=\"plot\">"))
            assertTrue(source, html.endsWith("</div>"))
            for (match in attribute.findAll(html)) {
                val text = match.groupValues[1]
                assertTrue("$source → $text", text.toDoubleOrNull()?.isFinite() == true)
            }
            for (run in Regex("points=\"([^\"]*)\"").findAll(html)) {
                for (pair in run.groupValues[1].split(" ")) {
                    val halves = pair.split(",")
                    assertEquals(pair, 2, halves.size)
                    assertTrue(pair, halves[0].toDoubleOrNull()?.isFinite() == true)
                    assertTrue(pair, halves[1].toDoubleOrNull()?.isFinite() == true)
                }
            }
        }
    }

    @Test fun survivesAFigureSqueezedToTheSmallestCanvas() {
        // Title, both axis labels and a legend on a 160 × 120 canvas would
        // compute a negative plot area without `fitMargins`.
        val tiny = Plot.plotSVG(
            listOf("width: 160", "height: 120", "title: T", "xlabel: x", "ylabel: y", "legend: on", "a = x")
                .joinToString("\n"),
        )
        assertTrue(tiny.contains("viewBox=\"0 0 160 120\""))
        assertFalse(tiny.contains("NaN"))
        // The plot area is still a real rectangle, inside the canvas.
        val rect = Regex("<rect x=\"([\\d.]+)\" y=\"([\\d.]+)\" width=\"([\\d.]+)\" height=\"([\\d.]+)\"")
            .find(tiny)
        assertNotNull(rect)
        val (x, y, w, h) = rect!!.groupValues.drop(1).map { it.toDouble() }
        assertTrue(w >= 40)
        assertTrue(h >= 40)
        assertTrue(x + w <= 160)
        assertTrue(y + h <= 120)
    }

    // MARK: - §8 The renderer, the settings and every export path

    private val fence = listOf("```plot", "x: -10..10", "sin(x)", "```").joinToString("\n")

    @Test fun dispatchesTheFenceToAPlotContainer() {
        val html = MarkdownHtml.document(fence, "t", dark = false)
        assertTrue(html.contains("<div class=\"plot\"><svg"))
        // The class is exactly `plot`, which keeps all five engine probes false:
        // a plot-only document loads no engine at all, and there is no `needs`
        // flag to add.
        for (engine in listOf("katex.min.js", "mermaid.min.js", "viz-global.js", "highlight.min.js")) {
            assertFalse(engine, html.contains(engine))
        }
        assertFalse(html.contains("class=\"language-"))
    }

    @Test fun isStyledByBothStylesheetsTheSharedOneAndTheEpubsOwn() {
        // Two sheets, because the EPUB carries a hand-written stylesheet of its
        // own (`Epub.EPUB_CSS`) that the shared one never reaches — the one
        // edit site the two Apple ports do not have.
        val exported = MarkdownHtml.document(fence, "t", dark = false)
        assertTrue(exported.contains(".mermaid, .plantuml, .graphviz, .plot, .md-mathd {"))
        assertTrue(
            exported.contains(
                ".mermaid svg, .plantuml svg, .graphviz svg, .plot svg { max-width: 100%; height: auto; }",
            ),
        )
        assertTrue(me.nettrash.md.book.EPUB_CSS.contains(".plot svg { max-width: 100%; height: auto; }"))
    }

    @Test fun offersTheFigureToTheSvgExport() {
        val document = listOf(fence, "", "```dot", "digraph {}", "```").joinToString("\n")
        val found = DiagramSvg.diagrams(document)
        assertEquals(listOf(DiagramSvg.Kind.PLOT, DiagramSvg.Kind.GRAPHVIZ), found.map { it.kind })
        assertEquals("Plot", found[0].typeName)
        assertEquals("Plot: x: -10..10", found[0].menuTitle)
        // A quoted plot keeps its place, because the renderer recurses into
        // quotes.
        assertEquals(
            listOf(DiagramSvg.Kind.PLOT),
            DiagramSvg.diagrams(listOf("> ```plot", "> sin(x)", "> ```").joinToString("\n")).map { it.kind },
        )
        // The DOM query that pairs with this walk lives in `ui/Exporter`
        // (`pre.mermaid, div.plantuml, div.graphviz, div.plot`) and is
        // device-only, so it is not reachable from a JVM test — the reference
        // suite asserts its own `DIAGRAM_SELECTOR` here instead. The two must
        // keep agreeing about what a diagram is, or every later figure exports
        // as the wrong one.
    }

    @Test fun savesAsAStandaloneSvgWithoutAFixUp() {
        // The root already carries `xmlns`, `width` and `height`, so the only
        // thing the writer adds is the XML prolog.
        val file = DiagramSvg.standaloneDocument(Plot.plotSVG("sin(x)"))
        assertTrue(file.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns="))
        assertTrue(file.contains("width=\"600\" height=\"400\""))
    }

    @Test fun keepsTheSourceInTheLatexExportUnderAComment() {
        val tex = LaTeXExport.document(fence)
        assertTrue(tex.contains("% plot diagram source"))
        assertTrue(tex.contains("\\begin{verbatim}"))
        assertTrue(tex.contains("sin(x)"))
    }

    @Test fun passesTheEpubsXhtmlFixerUntouchedAndAsksForPropertiesSvg() {
        // The fixer has never seen an SVG before: `toXhtml` self-closes void
        // elements with an *unanchored* alternation, so `<line>` and
        // `<polyline>` are exactly the shapes to check before trusting it.
        val body = documentBody(MarkdownHtml.document(fence, "t", dark = false))
        assertTrue(body.contains("<line "))
        assertTrue(body.contains("<polyline "))
        assertEquals(body, toXhtml(body))

        // EPUB 3 requires the reserved property on any content document holding
        // an `<svg>`; without it EPUBCheck reports OPF-014 and the book is
        // invalid.
        val withSvg = EpubUnit("content.xhtml", "t", toXhtml(body))
        val withoutSvg = EpubUnit("content.xhtml", "t", "<p>plain</p>")
        assertTrue(
            contentOpf(EpubBook("t", withSvg, emptyList(), emptyList(), emptyList()), "i", "m").contains(
                "<item id=\"content\" href=\"content.xhtml\" " +
                    "media-type=\"application/xhtml+xml\" properties=\"svg\"/>",
            ),
        )
        // …and a document without one is still emitted bare.
        assertTrue(
            contentOpf(EpubBook("t", withoutSvg, emptyList(), emptyList(), emptyList()), "i", "m").contains(
                "<item id=\"content\" href=\"content.xhtml\" media-type=\"application/xhtml+xml\"/>",
            ),
        )
    }

    @Test fun keepsTheLiteralSvgTagOutOfTheStylesheetTheOpfHeuristicSearchesFor() {
        // `contentOpf` decides `properties="svg"` by searching a content
        // document for the four characters `<svg`, which is only sound while
        // nothing *but* a figure puts them there. The stylesheet is
        // interpolated into every document's <style>, so a `<svg>` written in
        // one of its comments would be in every document this renderer emits —
        // harmless only because the EPUB body excludes the head, which is one
        // refactor of `documentBody` away from being a silent false positive on
        // every book. So the string is not allowed in the sheet at all.
        val plain = MarkdownHtml.document("just prose\n", "t", dark = false)
        assertFalse("a plot-free document must not contain the OPF marker", plain.contains("<svg"))
        for (dark in listOf(false, true)) {
            for (export in listOf(false, true)) {
                assertFalse(
                    "stylesheet dark=$dark export=$export",
                    MarkdownHtml.document("x\n", "t", dark = dark, export = export).contains("<svg"),
                )
            }
        }
    }

    @Test fun theEpubContentDocumentHoldingAPlotIsWellFormedXml() {
        // The whole reason every author string is escaped: an EPUB content
        // document is XHTML, which is XML, and one raw `&` or `<` makes the
        // book unopenable rather than merely ugly. A hostile title, both axis
        // labels and a legend label go through the same parser a reader would
        // use — with no network access, so a DTD reference could not be
        // resolved even if one were emitted.
        val fence = listOf(
            "```plot",
            "x: -10..10",
            "title: A & B <c> \"d\"",
            "xlabel: <x>",
            "ylabel: &y;",
            "p & q = sin(x)",
            "```",
        ).joinToString("\n")
        val body = toXhtml(documentBody(MarkdownHtml.document(fence, "t", dark = false)))
        val document = javax.xml.parsers.DocumentBuilderFactory.newInstance()
            .newDocumentBuilder()
            .parse(org.xml.sax.InputSource(java.io.StringReader(xhtmlDocument("t", body))))
        assertEquals(1, document.getElementsByTagName("svg").length)
        assertEquals("A & B <c> \"d\"", document.getElementsByTagName("title").item(1).textContent)
    }

    // MARK: - §8b The render cache

    /**
     * Why this exists at all: `plot` is the only rich block drawn *in the
     * renderer*, synchronously, so the live preview pays for every figure in a
     * document on every keystroke — the 0.35 s debounce delays the WebView
     * reload, not the render. Measured in a release build: 4.87 ms for one
     * default figure, 36 ms for an eight-series one, 187 ms for a document of
     * four of those and 289 ms for ten `samples: 5000` figures. The per-fence
     * caps bound a fence, not a document.
     *
     * The fix is a memo, because [Plot.renderPlot] is a pure function of its
     * fence text: while an author types a sentence, every plot in the document
     * is a hit. These tests are the whole assurance that it is really a memo —
     * a cache is invisible in the output by construction, so `renderCount`
     * (drawings, not calls) is what makes a hit observable.
     */
    @Test fun rendersEachDistinctFenceOnceAndServesTheRepeatFromTheCache() {
        Plot.resetRenderCacheForTest()
        val source = "x: -10..10\nsin(x)"

        val first = Plot.renderPlot(source)
        assertEquals(1L, Plot.renderCacheStateForTest().second)

        // Twenty more calls with the identical text — the preview's keystroke
        // loop, in miniature. One drawing, twenty identical answers.
        repeat(20) { assertEquals(first, Plot.renderPlot(source)) }
        assertEquals(1L, Plot.renderCacheStateForTest().second)
        assertEquals(1, Plot.renderCacheStateForTest().first)

        // A different fence is a different key: the memo is on the text, not on
        // "the last thing rendered".
        Plot.renderPlot("x: -10..10\ncos(x)")
        assertEquals(2L, Plot.renderCacheStateForTest().second)
        assertEquals(first, Plot.renderPlot(source))
        assertEquals(2L, Plot.renderCacheStateForTest().second)
    }

    @Test fun cachesFailuresToo() {
        // A half-typed fence is a parse failure, and that is the state a fence
        // spends most of its life in while it is being written. Re-running the
        // parser on every keystroke to re-learn "expected ')'" is exactly the
        // cost this is here to remove, so the failure path is memoised on the
        // same terms as the success path.
        Plot.resetRenderCacheForTest()
        val broken = "x: -10..10\nsin(x"

        val first = Plot.renderPlot(broken)
        assertTrue(first.contains("plot: expected ')'"))
        assertEquals(1L, Plot.renderCacheStateForTest().second)
        repeat(10) { assertEquals(first, Plot.renderPlot(broken)) }
        assertEquals(1L, Plot.renderCacheStateForTest().second)

        // And the empty fence, which is not an error and draws nothing.
        Plot.renderPlot("")
        Plot.renderPlot("")
        assertEquals(2L, Plot.renderCacheStateForTest().second)
    }

    @Test fun evictsTheLeastRecentlyUsedFenceAtThirtyTwoEntries() {
        Plot.resetRenderCacheForTest()
        // 32 is what md.vscode's preview client already uses for its diagram
        // cache; the four ports bound the same thing the same way. Bounded at
        // all because an editing session types thousands of distinct
        // intermediate fences and never asks for one of them twice.
        val fences = (0 until 32).map { "x: -10..10\nsin(x)+$it" }
        for (source in fences) Plot.renderPlot(source)
        var state = Plot.renderCacheStateForTest()
        assertEquals(32, state.first)
        assertEquals(32L, state.second)

        // Touch the oldest so it is no longer the eldest — a read counts as a
        // use, which is what keeps the figures a document is *showing* resident
        // while the junk between keystrokes ages out.
        Plot.renderPlot(fences[0])
        assertEquals(32L, Plot.renderCacheStateForTest().second)

        // The thirty-third entry evicts fences[1], not fences[0].
        Plot.renderPlot("x: -10..10\ncos(x)")
        state = Plot.renderCacheStateForTest()
        assertEquals(32, state.first)
        assertEquals(33L, state.second)
        assertTrue(state.third.contains(fences[0]))
        assertFalse(state.third.contains(fences[1]))

        // …and asking for the evicted one draws it again, which is the proof
        // that it really left rather than merely stopped being counted.
        Plot.renderPlot(fences[1])
        assertEquals(34L, Plot.renderCacheStateForTest().second)
        assertEquals(32, Plot.renderCacheStateForTest().first)
    }

    @Test fun theCacheNeverChangesWhatAFenceRendersTo() {
        // The one thing a memo must not do. Every recorded figure, drawn cold
        // and then drawn again through a full cache, byte for byte.
        val sources = rows("svg").map { row ->
            // The literal the generator wrote, as `assertFigure` uses it — a
            // re-formatted double would not always re-parse.
            "x: ${row["xMin"].raw()}..${row["xMax"].raw()}\n" +
                "y: ${row["yMin"].raw()}..${row["yMax"].raw()}\n${row["expr"].string()}"
        }
        Plot.resetRenderCacheForTest()
        val cold = sources.map { Plot.renderPlot(it) }
        // 22 recorded figures against a 32-entry cache: run them twice more so
        // the second pass is served entirely from it.
        repeat(2) {
            for ((index, source) in sources.withIndex()) {
                assertEquals(cold[index], Plot.renderPlot(source))
            }
        }
        assertEquals(sources.size.toLong(), Plot.renderCacheStateForTest().second)
        // Uncached, from the same input, is the same bytes as cached.
        Plot.resetRenderCacheForTest()
        for ((index, source) in sources.withIndex()) {
            assertEquals(cold[index], Plot.renderPlot(source))
        }
    }

    // MARK: - §9 The figure itself, byte for byte

    @Test fun drawsTheSpecsOwnExampleAsRecorded() {
        // The whole SVG of one document, pinned — and pinned against
        // **md.vscode's own golden file**, byte for byte, which is the entire
        // cross-port parity claim: same fence, same 31,647 bytes, in TypeScript
        // and in Kotlin. Not a specification and not documentation: a tripwire,
        // so that a change to a coordinate, an opacity or an attribute order
        // shows up as a diff to read rather than as nothing at all.
        val source = listOf(
            "x: -10..10",
            "y: -2..2",
            "title: Damped oscillation",
            "xlabel: x",
            "ylabel: amplitude",
            "envelope = exp(-abs(x)/5)",
            "sin(x) * exp(-abs(x)/5)",
        ).joinToString("\n")
        val golden = checkNotNull(
            javaClass.classLoader?.getResourceAsStream("plot-damped-oscillation.svg"),
        ) { "missing plot-damped-oscillation.svg" }.readBytes().toString(Charsets.UTF_8)
        val got = Plot.renderPlot(source) + "\n"
        if (got != golden) {
            // Name the first difference rather than dumping 31 KB twice.
            var index = 0
            while (index < got.length && index < golden.length && got[index] == golden[index]) index++
            val from = maxOf(0, index - 60)
            throw AssertionError(
                "golden differs at byte $index (ours ${got.length} bytes, golden ${golden.length})\n" +
                    "ours:   …${got.substring(from, minOf(got.length, index + 60))}\n" +
                    "golden: …${golden.substring(from, minOf(golden.length, index + 60))}",
            )
        }
        assertEquals(31647, golden.toByteArray(Charsets.UTF_8).size)
    }

    // MARK: - §10 Resource limits and degenerate magnitudes

    // Each of these was found by an adversarial pass against the reference, and
    // each is a way it could have taught the same defect to this port. A stack
    // overflow is an exception there and a crash here, so the guards matter more
    // in this file than in that one.

    @Test fun drawsASeriesWhoseValuesOverflowThePaddedRange() {
        // `high - low` overflows for a series straddling ~1e308, which made
        // every sy() NaN and emitted points="40.00,NaN …" — a curve that
        // vanished with nothing to say why.
        val out = Plot.renderPlot("x: -10..10\nx*1e307")
        assertFalse(out.contains("NaN"))
        assertTrue(out.contains("<polyline"))
    }

    @Test fun leavesAHugeButNarrowRangeExactlyAsAsked() {
        // The guard must fire on an overflowing *width*, not on a large bound:
        // [1.69e308, 1.71e308] is only 2e306 wide and is perfectly drawable.
        val out = Plot.renderPlot("x: -1..1\ny: 1.69e308..1.71e308\n1.7e308")
        assertFalse(out.contains("NaN"))
        assertTrue(out.contains("<polyline"))
    }

    @Test fun reportsDeepNestingAsAPlotLineNotAStackOverflow() {
        val source = "x: -1..1\n" + "(".repeat(5000) + "x" + ")".repeat(5000)
        assertTrue(Plot.renderPlot(source).contains("plot: expression nested too deeply"))
    }

    @Test fun reportsALongFlatChainTooWhichTheDepthGuardCannotSee() {
        // `x+x+x+…` parses at constant depth through the left-associative loop
        // and then overflows the stack in the evaluator, so depth alone is not
        // enough.
        val source = "x: -1..1\nx" + "+x".repeat(20000)
        assertTrue(Plot.renderPlot(source).contains("plot: expression too large"))
    }

    @Test fun capsTheSeriesCountTheOneInputWithNoClamp() {
        val source = "x: -1..1\n" + (1..1000).joinToString("\n") { "x*$it" }
        assertTrue(Plot.renderPlot(source).contains("plot: too many series"))
    }

    @Test fun drawsTheAxesADirectivesOnlyBlockDescribes() {
        // Not an empty block: the author wrote three lines. Returning an empty
        // container would swallow them, and the family rule is never a hole.
        val out = Plot.renderPlot("x: -10..10\ntitle: My chart\nylabel: y")
        assertTrue(out.contains("<svg"))
        assertTrue(out.contains("My chart"))
    }

    @Test fun stillDrawsNothingForAGenuinelyEmptyBlock() {
        assertEquals("<div class=\"plot\"></div>", Plot.renderPlot(""))
    }

    // MARK: - Assertion helpers

    private fun assertThrowsPlotError(what: String, body: () -> Unit) {
        try {
            body()
        } catch (error: Plot.PlotError) {
            assertNotNull(error.message)
            return
        }
        throw AssertionError("`$what` should have been a PlotError")
    }

    private fun assertMessage(fragment: String, body: () -> Unit) {
        try {
            body()
        } catch (error: Plot.PlotError) {
            assertTrue(
                "wanted a message containing \"$fragment\", got \"${error.message}\"",
                error.message.orEmpty().contains(fragment),
            )
            return
        }
        throw AssertionError("nothing was thrown, wanted \"$fragment\"")
    }

    // MARK: - Small text helpers, hand-written so a regex cannot drift

    private fun countOf(text: String, needle: String): Int {
        var count = 0
        var index = text.indexOf(needle)
        while (index >= 0) {
            count++
            index = text.indexOf(needle, index + needle.length)
        }
        return count
    }

    /** Every span between [opener] and the next [closer], in order. */
    private fun allGroups(text: String, opener: String, closer: String): List<String> {
        val out = ArrayList<String>()
        var index = text.indexOf(opener)
        while (index >= 0) {
            val start = index + opener.length
            val end = text.indexOf(closer, start)
            if (end < 0) break
            out.add(text.substring(start, end))
            index = text.indexOf(opener, end)
        }
        return out
    }
}

// MARK: - A JSON reader
//
// Thirty lines of recursive descent, because the unit-test classpath has JUnit
// and nothing else: `org.json` is Android's, and under `./gradlew test` every
// one of its methods throws "not mocked". A number keeps its source text as
// well as its value, so a range can be rebuilt from the literal the generator
// wrote rather than from a re-formatted double.

internal class JsonValue private constructor(
    private val kind: Int,
    private val text: String,
    private val fields: Map<String, JsonValue>?,
    private val items: List<JsonValue>?,
) {
    val isString: Boolean get() = kind == STRING

    fun string(): String {
        demand(kind == STRING, "string")
        return text
    }

    fun stringOrNull(): String? = if (kind == NULL) null else string()

    fun number(): Double {
        demand(kind == NUMBER, "number")
        return text.toDouble()
    }

    fun int(): Int = number().toInt()

    /** The literal the generator wrote, so a rebuilt range is bit-identical. */
    fun raw(): String {
        demand(kind == NUMBER, "number")
        return text
    }

    fun array(): List<JsonValue> {
        demand(kind == ARRAY, "array")
        return items!!
    }

    fun strings(): List<String> = array().map { it.string() }

    operator fun get(key: String): JsonValue {
        demand(kind == OBJECT, "object")
        return fields!![key] ?: throw AssertionError("no key '$key'")
    }

    override fun toString(): String = text

    private fun demand(condition: Boolean, wanted: String) {
        if (!condition) throw AssertionError("not a $wanted: $text")
    }

    internal companion object {
        const val OBJECT = 0
        const val ARRAY = 1
        const val STRING = 2
        const val NUMBER = 3
        const val LITERAL = 4
        const val NULL = 5

        fun obj(fields: Map<String, JsonValue>) = JsonValue(OBJECT, "", fields, null)
        fun arr(items: List<JsonValue>) = JsonValue(ARRAY, "", null, items)
        fun str(text: String) = JsonValue(STRING, text, null, null)
        fun num(text: String) = JsonValue(NUMBER, text, null, null)
        fun literal(text: String) =
            JsonValue(if (text == "null") NULL else LITERAL, text, null, null)
    }
}

internal object Json {

    fun parse(text: String): JsonValue {
        val reader = Reader(text)
        reader.skipSpace()
        val value = reader.value()
        reader.skipSpace()
        return value
    }

    private class Reader(private val text: String) {
        private var index = 0

        fun skipSpace() {
            while (index < text.length && text[index].code <= ' '.code) index++
        }

        fun value(): JsonValue {
            skipSpace()
            return when (text[index]) {
                '{' -> obj()
                '[' -> arr()
                '"' -> JsonValue.str(string())
                't', 'f', 'n' -> literal()
                else -> number()
            }
        }

        private fun obj(): JsonValue {
            index++ // '{'
            val fields = LinkedHashMap<String, JsonValue>()
            skipSpace()
            if (text[index] == '}') {
                index++
                return JsonValue.obj(fields)
            }
            while (true) {
                skipSpace()
                val key = string()
                skipSpace()
                index++ // ':'
                fields[key] = value()
                skipSpace()
                val c = text[index]
                index++
                if (c == '}') return JsonValue.obj(fields)
            }
        }

        private fun arr(): JsonValue {
            index++ // '['
            val items = ArrayList<JsonValue>()
            skipSpace()
            if (text[index] == ']') {
                index++
                return JsonValue.arr(items)
            }
            while (true) {
                items.add(value())
                skipSpace()
                val c = text[index]
                index++
                if (c == ']') return JsonValue.arr(items)
            }
        }

        private fun string(): String {
            index++ // '"'
            val out = StringBuilder()
            while (text[index] != '"') {
                val c = text[index]
                if (c == '\\') {
                    index++
                    when (val escape = text[index]) {
                        '"', '\\', '/' -> out.append(escape)
                        'b' -> out.append('\b')
                        'f' -> out.append('\u000C')
                        'n' -> out.append('\n')
                        'r' -> out.append('\r')
                        't' -> out.append('\t')
                        'u' -> {
                            out.append(text.substring(index + 1, index + 5).toInt(16).toChar())
                            index += 4
                        }
                        else -> throw AssertionError("bad escape \\$escape")
                    }
                } else {
                    out.append(c)
                }
                index++
            }
            index++ // '"'
            return out.toString()
        }

        private fun literal(): JsonValue {
            val start = index
            while (index < text.length && text[index] in 'a'..'z') index++
            return JsonValue.literal(text.substring(start, index))
        }

        private fun number(): JsonValue {
            val start = index
            while (index < text.length && (
                    text[index] in '0'..'9' || text[index] == '-' || text[index] == '+' ||
                        text[index] == '.' || text[index] == 'e' || text[index] == 'E'
                    )
            ) {
                index++
            }
            return JsonValue.num(text.substring(start, index))
        }
    }
}
