/*
 * SmartTypingTest.kt
 * md (Android)
 *
 * SmartTyping against the shared oracle.
 *
 * WHERE THE EXPECTATIONS COME FROM
 * --------------------------------
 * `src/test/resources/typing-vectors.json` is the cross-port vector file of
 * SmartTyping SPEC.md v1 (§4): 512 `enter` and 838 `capitalize` vectors,
 * generated by the TypeScript reference the spec was written against, and
 * copied byte for byte into every repo (md, md.macOS, md.win). Offsets are
 * UTF-16 units; "no edit" is the JSON literal `null`, never the string
 * `"none"`; every unit outside printable ASCII is a `\uXXXX` escape, so no
 * editor can normalise an invisible one away.
 *
 * Every vector is asserted, and a failing one is reported by its `id` with
 * the expected and the actual result side by side. There is no correction
 * table here: the oracle IS the specification (a disputed vector changes in
 * the JSON first, in one commit across the repos), so a port that disagrees
 * with a vector is wrong until the JSON says otherwise.
 *
 * Two things the JSON cannot carry are tested natively (§4.2): a lone
 * surrogate, which the Swift port cannot even represent, and a caret between
 * the halves of a surrogate pair.
 *
 * JSON is read by the hand-written parser at the foot of `PlotTest.kt` — the
 * unit-test classpath carries JUnit and nothing else, and `org.json` is the
 * "not mocked" stub under `./gradlew test`.
 */

package me.nettrash.md.markdown

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class SmartTypingTest {

    // MARK: - The corpus

    private val vectors: JsonValue by lazy { loadVectors() }

    private fun loadVectors(): JsonValue {
        val stream = checkNotNull(javaClass.classLoader?.getResourceAsStream("typing-vectors.json")) {
            "missing typing-vectors.json"
        }
        return Json.parse(stream.bufferedReader(Charsets.UTF_8).use { it.readText() })
    }

    private fun rows(key: String): List<JsonValue> = vectors[key].array()

    /** A string spelt the way the JSON spells it, so a failure message shows every invisible unit. */
    private fun show(s: String?): String {
        if (s == null) return "null"
        val out = StringBuilder("\"")
        for (ch in s) {
            val u = ch.code
            when {
                u == 0x22 -> out.append("\\\"")
                u == 0x5c -> out.append("\\\\")
                u == 0x0a -> out.append("\\n")
                u in 0x20..0x7e -> out.append(ch)
                else -> out.append("\\u").append(String.format("%04x", u))
            }
        }
        return out.append('"').toString()
    }

    private fun show(e: SmartTyping.EnterEdit?): String =
        if (e == null) "null"
        else "{location=${e.location}, length=${e.length}, replacement=${show(e.replacement)}, caret=${e.caret}}"

    private fun expectedEdit(row: JsonValue): SmartTyping.EnterEdit? {
        val expected = row["expected"]
        if (expected.isNull) return null
        return SmartTyping.EnterEdit(
            expected["location"].int(),
            expected["length"].int(),
            expected["replacement"].string(),
            expected["caret"].int(),
        )
    }

    // MARK: - §1 enter — every vector

    @Test fun everyEnterVectorMatches() {
        val recorded = rows("enter")
        assertEquals("the _meta count", vectors["_meta"]["counts"]["enter"].int(), recorded.size)
        assertEquals(512, recorded.size)
        val failures = ArrayList<String>()
        for (row in recorded) {
            val id = row["id"].string()
            val want = expectedEdit(row)
            val got = SmartTyping.enter(row["text"].string(), row["start"].int(), row["end"].int())
            if (got != want) failures.add("$id: expected ${show(want)}, actual ${show(got)}")
        }
        assertTrue(
            "${failures.size} of ${recorded.size} enter vectors failed:\n" + failures.joinToString("\n"),
            failures.isEmpty(),
        )
    }

    // MARK: - §2 capitalize — every vector

    @Test fun everyCapitalizeVectorMatches() {
        val recorded = rows("capitalize")
        assertEquals("the _meta count", vectors["_meta"]["counts"]["capitalize"].int(), recorded.size)
        assertEquals(838, recorded.size)
        val failures = ArrayList<String>()
        for (row in recorded) {
            val id = row["id"].string()
            val want = row["expected"].stringOrNull()
            val got = SmartTyping.capitalize(
                row["text"].string(), row["start"].int(), row["end"].int(), row["typed"].string(),
            )
            if (got != want) failures.add("$id: expected ${show(want)}, actual ${show(got)}")
        }
        assertTrue(
            "${failures.size} of ${recorded.size} capitalize vectors failed:\n" + failures.joinToString("\n"),
            failures.isEmpty(),
        )
    }

    @Test fun theCorpusIsTheOneTheSpecDescribes() {
        // 1350 vectors, ids unique across both arrays, every `typed` one scalar.
        val ids = HashSet<String>()
        for (key in listOf("enter", "capitalize")) {
            for (row in rows(key)) assertTrue("duplicate id ${row["id"]}", ids.add(row["id"].string()))
        }
        assertEquals(1350, ids.size)
        for (row in rows("capitalize")) {
            val typed = row["typed"].string()
            assertEquals("${row["id"]}: typed must be one scalar", 1, typed.codePointCount(0, typed.length))
        }
    }

    // MARK: - Hand-written, for readability

    @Test fun aBulletContinues() {
        assertEquals(SmartTyping.EnterEdit(6, 0, "\n- ", 9), SmartTyping.enter("- item", 6, 6))
        assertEquals(SmartTyping.EnterEdit(6, 0, "\n4) ", 10), SmartTyping.enter("3) two", 6, 6))
        assertEquals(SmartTyping.EnterEdit(10, 0, "\n- [ ] ", 17), SmartTyping.enter("- [x] done", 10, 10))
    }

    @Test fun anEmptyItemEndsTheList() {
        // `- a` / `- |` → the empty item's line becomes empty, caret there.
        assertEquals(SmartTyping.EnterEdit(4, 2, "", 4), SmartTyping.enter("- a\n- ", 6, 6))
        // …and a nested empty item outdents to its parent's marker first.
        assertEquals(SmartTyping.EnterEdit(4, 4, "- ", 6), SmartTyping.enter("- a\n  - ", 8, 8))
        // A quoted empty item ends to the quote line.
        assertEquals(SmartTyping.EnterEdit(0, 4, "> ", 2), SmartTyping.enter("> - ", 4, 4))
    }

    @Test fun aTableRowInsertsARowBelow() {
        val table = "| a | b |\n|---|---|\n| 1 | 2 |"
        // Enter at the end of a body row (unit 29): a new `|  |  |` after it, caret in its first cell.
        assertEquals(SmartTyping.EnterEdit(29, 0, "\n|  |  |", 32), SmartTyping.enter(table, 29, 29))
        // Enter mid-row does the same — the row is never split.
        assertEquals(SmartTyping.EnterEdit(29, 0, "\n|  |  |", 32), SmartTyping.enter(table, 24, 24))
        // Enter anywhere in the header row: the row goes under the delimiter row (which ends at 19).
        assertEquals(SmartTyping.EnterEdit(19, 0, "\n|  |  |", 22), SmartTyping.enter(table, 3, 3))
        // A blank last row ends the table: the row's line (20–27) becomes empty.
        assertEquals(SmartTyping.EnterEdit(20, 7, "", 20), SmartTyping.enter("| a | b |\n|---|---|\n|  |  |", 27, 27))
    }

    @Test fun aCapitalAfterAPeriodAndASpace() {
        assertEquals("W", SmartTyping.capitalize("Hello. ", 7, 7, "w"))
        assertEquals("H", SmartTyping.capitalize("", 0, 0, "h"))
        assertEquals("J", SmartTyping.capitalize("Notes\n", 6, 6, "j"))
        assertNull(SmartTyping.capitalize("e.g. ", 5, 5, "n"))
        assertNull(SmartTyping.capitalize("wait... ", 8, 8, "w"))
        assertNull(SmartTyping.capitalize("don'", 4, 4, "t"))
    }

    @Test fun noCapitalInsideAFence() {
        assertNull(SmartTyping.capitalize("```\ncode. ", 10, 10, "n"))
        assertNull(SmartTyping.capitalize("```\n", 4, 4, "t"))
        assertNull(SmartTyping.enter("```\n- item", 10, 10))
        // The line after the closer is prose again.
        assertEquals("T", SmartTyping.capitalize("```\ncode\n```\n", 13, 13, "t"))
    }

    // MARK: - What the JSON cannot carry (§4.2): native per-port tests

    @Test fun aLoneSurrogateIsNoLetter() {
        // A lone surrogate is a scalar of category Cs (§0.1): it is never a
        // lowercase letter, so typing one changes nothing…
        assertNull(SmartTyping.capitalize("", 0, 0, "\uD800"))
        assertNull(SmartTyping.capitalize("Hello. ", 7, 7, "\uDC00"))
        // …and in the text it belongs to none of the classes: not WS19, not a
        // letter, not an opener — `\uDC00` before the caret is an ordinary
        // token with no whitespace before it (rule B step 1 fails).
        assertNull(SmartTyping.capitalize("\uDC00", 1, 1, "t"))
        // A lone high surrogate is content after a marker like any other unit.
        assertEquals(SmartTyping.EnterEdit(3, 0, "\n- ", 6), SmartTyping.enter("- \uD83D", 3, 3))
    }

    @Test fun aCaretBetweenTheHalvesOfASurrogatePairIsNull() {
        val text = "- 😀 x" // `- 😀 x`
        assertNotNull(SmartTyping.enter(text, 4, 4))
        assertNull(SmartTyping.enter(text, 3, 3))
        assertNull(SmartTyping.enter(text, 2, 3))
        assertNull(SmartTyping.enter(text, 3, 6))
        assertNull(SmartTyping.capitalize(text, 3, 3, "t"))
        assertNull(SmartTyping.capitalize(text, 2, 3, "t"))
        // Likewise between the CR and the LF of one terminator (§0.2).
        assertNull(SmartTyping.enter("- a\r\n- b", 4, 4))
        assertNull(SmartTyping.capitalize("- a\r\n- b", 4, 4, "t"))
    }

    @Test fun offsetsOutOfRangeAreNull() {
        assertNull(SmartTyping.enter("- item", 7, 7))
        assertNull(SmartTyping.enter("- item", -1, 0))
        assertNull(SmartTyping.capitalize("- item", 0, 7, "t"))
        // A reversed selection is normalised, not rejected.
        assertEquals(SmartTyping.enter("- item", 2, 6), SmartTyping.enter("- item", 6, 2))
    }

    // MARK: - Informational: the §0.14 cost contract on a 1 MB document

    /**
     * Both functions run on the UI thread on every keystroke, so a one-line
     * edit at the end of a big document has to stay cheap. This logs the
     * timing of each call on a document of just over 1 MB with the caret at
     * its end (the worst case for the forward state scan). It is not a
     * wall-clock assertion — CI machines are slower and a bound would be a
     * flake generator — but the numbers are in the test report to read.
     */
    @Test fun aOneMegabyteDocumentIsHandledInMilliseconds() {
        val chunk = buildString {
            append("# Section\n\n")
            append("Some prose that runs on for a while. Another sentence follows it here.\n")
            append("A third line, hard-wrapped the way notes are. And a fourth one.\n\n")
            append("- first item\n- second item\n  - nested item\n\n")
            append("| col a | col b |\n|-------|-------|\n| 1     | 2     |\n\n")
            append("> a quoted line\n> and another\n\n")
            append("```\ncode();\n```\n\n")
        }
        val doc = buildString {
            while (length < 1 shl 20) append(chunk)
            append("- last item. ")
        }
        assertTrue(doc.length >= 1 shl 20)
        val caret = doc.length

        // One warm-up call each, then the fastest of three timed runs.
        SmartTyping.enter(doc, caret, caret)
        SmartTyping.capitalize(doc, caret, caret, "t")
        var enterNs = Long.MAX_VALUE
        var capNs = Long.MAX_VALUE
        var edit: SmartTyping.EnterEdit? = null
        var cap: String? = null
        repeat(3) {
            var t0 = System.nanoTime()
            edit = SmartTyping.enter(doc, caret, caret)
            enterNs = minOf(enterNs, System.nanoTime() - t0)
            t0 = System.nanoTime()
            cap = SmartTyping.capitalize(doc, caret, caret, "t")
            capNs = minOf(capNs, System.nanoTime() - t0)
        }
        // The shape of the answers, so the timing is of a real call and not a short-circuit.
        assertEquals(SmartTyping.EnterEdit(caret, 0, "\n- ", caret + 3), edit)
        assertEquals("T", cap)
        println(
            "SmartTyping on ${doc.length} units (${doc.count { it == '\n' } + 1} lines), caret at the end: " +
                "enter %.1f ms, capitalize %.1f ms (fastest of 3)".format(enterNs / 1e6, capNs / 1e6),
        )
    }
}
